"""
Prometheus Metrics — FastAPI instrumentation.
Custom business metrics for TeamGenie AI.
"""

from __future__ import annotations

import time
from typing import Callable

from fastapi import Request, Response
from prometheus_client import (
    Counter,
    Histogram,
    Gauge,
    generate_latest,
    CONTENT_TYPE_LATEST,
)
from starlette.responses import Response as StarletteResponse

# ---------------------------------------------------------------------------
# HTTP Metrics
# ---------------------------------------------------------------------------
HTTP_REQUESTS_TOTAL = Counter(
    "http_requests_total",
    "Total HTTP requests",
    ["method", "path", "status"],
)

HTTP_REQUEST_DURATION = Histogram(
    "http_request_duration_seconds",
    "HTTP request duration in seconds",
    ["method", "path"],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
)

# ---------------------------------------------------------------------------
# Business Metrics
# ---------------------------------------------------------------------------
TEAMS_GENERATED = Counter(
    "teams_generated_total",
    "Total teams generated by AI agents",
    ["risk_level", "cached"],
)

TEAM_GENERATION_DURATION = Histogram(
    "team_generation_duration_seconds",
    "Time to generate a team via multi-agent pipeline",
    buckets=[0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 10.0, 15.0],
)

PREDICTION_ACCURACY = Gauge(
    "prediction_accuracy_rate",
    "Current rolling prediction accuracy",
)

ACTIVE_WEBSOCKETS = Gauge(
    "active_websocket_connections",
    "Number of active WebSocket connections",
)

RATE_LIMIT_EXCEEDED = Counter(
    "rate_limit_exceeded_total",
    "Number of rate-limited requests",
    ["tier"],
)

RAG_QUERY_DURATION = Histogram(
    "rag_query_duration_seconds",
    "RAG pipeline query duration",
    buckets=[0.05, 0.1, 0.3, 0.5, 1.0, 2.0],
)

CACHE_HITS = Counter("cache_hits_total", "Cache hits", ["cache_type"])
CACHE_MISSES = Counter("cache_misses_total", "Cache misses", ["cache_type"])


# ---------------------------------------------------------------------------
# Metrics Middleware
# ---------------------------------------------------------------------------
async def metrics_middleware(request: Request, call_next: Callable) -> Response:
    """Record HTTP request metrics."""
    if request.url.path == "/metrics":
        return await call_next(request)

    start = time.perf_counter()
    response = await call_next(request)
    duration = time.perf_counter() - start

    # Normalize path to avoid high-cardinality labels
    path = _normalize_path(request.url.path)

    HTTP_REQUESTS_TOTAL.labels(
        method=request.method,
        path=path,
        status=response.status_code,
    ).inc()

    HTTP_REQUEST_DURATION.labels(
        method=request.method,
        path=path,
    ).observe(duration)

    return response


def _normalize_path(path: str) -> str:
    """Replace dynamic segments with placeholders to limit label cardinality."""
    parts = path.strip("/").split("/")
    normalized = []
    for part in parts:
        if len(part) > 20 or part.replace("-", "").replace("_", "").isalnum() and not part.isalpha():
            normalized.append("{id}")
        else:
            normalized.append(part)
    return "/" + "/".join(normalized)


# ---------------------------------------------------------------------------
# Metrics Endpoint
# ---------------------------------------------------------------------------
async def metrics_endpoint(request: Request) -> StarletteResponse:
    """Expose Prometheus metrics at /metrics."""
    return StarletteResponse(
        content=generate_latest(),
        media_type=CONTENT_TYPE_LATEST,
    )
