"""
Prometheus Metrics — FastAPI instrumentation.
Custom business metrics for TeamGenie AI.
"""

from __future__ import annotations

import time
from typing import Callable

from fastapi import Request, Response

try:
    from prometheus_client import (
        Counter,
        Histogram,
        Gauge,
        generate_latest,
        CONTENT_TYPE_LATEST,
    )
    _PROMETHEUS_AVAILABLE = True
except ImportError:  # pragma: no cover
    _PROMETHEUS_AVAILABLE = False
    Counter = Histogram = Gauge = None  # type: ignore[assignment,misc]
    generate_latest = None  # type: ignore[assignment]
    CONTENT_TYPE_LATEST = "text/plain"  # type: ignore[assignment]

from starlette.responses import Response as StarletteResponse

# ---------------------------------------------------------------------------
# HTTP Metrics (only instantiated when prometheus_client is installed)
# ---------------------------------------------------------------------------
if _PROMETHEUS_AVAILABLE:
    HTTP_REQUESTS_TOTAL = Counter(
        "http_requests_total",
        "Total HTTP requests",
        ["method", "path", "status"],
    )

    HTTP_REQUEST_DURATION = Histogram(
        "http_request_duration_seconds",
        "HTTP request duration in seconds",
        ["method", "path"],
        buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
    )

    # ---------------------------------------------------------------------------
    # Business Metrics
    # ---------------------------------------------------------------------------
    TEAMS_GENERATED = Counter(
        "teams_generated_total",
        "Total teams generated by AI agents",
        ["risk_level", "cached"],
    )

    TEAM_GENERATION_DURATION = Histogram(
        "team_generation_duration_seconds",
        "Time to generate a team via multi-agent pipeline",
        buckets=[0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 10.0, 15.0],
    )

    PREDICTION_ACCURACY = Gauge(
        "prediction_accuracy_rate",
        "Current rolling prediction accuracy",
    )

    ACTIVE_WEBSOCKETS = Gauge(
        "active_websocket_connections",
        "Number of active WebSocket connections",
    )

    RATE_LIMIT_EXCEEDED = Counter(
        "rate_limit_exceeded_total",
        "Number of rate-limited requests",
        ["tier"],
    )

    RAG_QUERY_DURATION = Histogram(
        "rag_query_duration_seconds",
        "RAG pipeline query duration",
        buckets=[0.05, 0.1, 0.3, 0.5, 1.0, 2.0],
    )

    CACHE_HITS = Counter("cache_hits_total", "Cache hits", ["cache_type"])
    CACHE_MISSES = Counter("cache_misses_total", "Cache misses", ["cache_type"])
else:
    HTTP_REQUESTS_TOTAL = HTTP_REQUEST_DURATION = TEAMS_GENERATED = None  # type: ignore[assignment]
    TEAM_GENERATION_DURATION = PREDICTION_ACCURACY = ACTIVE_WEBSOCKETS = None  # type: ignore[assignment]
    RATE_LIMIT_EXCEEDED = RAG_QUERY_DURATION = CACHE_HITS = CACHE_MISSES = None  # type: ignore[assignment]


# ---------------------------------------------------------------------------
# Metrics Middleware
# ---------------------------------------------------------------------------
async def metrics_middleware(request: Request, call_next: Callable) -> Response:
    """Record HTTP request metrics."""
    if not _PROMETHEUS_AVAILABLE:
        return await call_next(request)

    if request.url.path == "/metrics":
        return await call_next(request)

    start = time.perf_counter()
    response = await call_next(request)
    duration = time.perf_counter() - start

    # Normalize path to avoid high-cardinality labels
    path = _normalize_path(request.url.path)

    HTTP_REQUESTS_TOTAL.labels(
        method=request.method,
        path=path,
        status=response.status_code,
    ).inc()

    HTTP_REQUEST_DURATION.labels(
        method=request.method,
        path=path,
    ).observe(duration)

    return response


def _normalize_path(path: str) -> str:
    """Replace dynamic segments with placeholders to limit label cardinality."""
    parts = path.strip("/").split("/")
    normalized = []
    for part in parts:
        if len(part) > 20 or part.replace("-", "").replace("_", "").isalnum() and not part.isalpha():
            normalized.append("{id}")
        else:
            normalized.append(part)
    return "/" + "/".join(normalized)


# ---------------------------------------------------------------------------
# Metrics Endpoint
# ---------------------------------------------------------------------------
async def metrics_endpoint(request: Request) -> StarletteResponse:
    """Expose Prometheus metrics at /metrics (falls back to empty response when prometheus_client not installed)."""
    if _PROMETHEUS_AVAILABLE:
        return StarletteResponse(
            content=generate_latest(),
            media_type=CONTENT_TYPE_LATEST,
        )
    return StarletteResponse(
        content="# prometheus_client not installed\n",
        media_type="text/plain; charset=utf-8",
    )
